# apiVersion: v1
# kind: Service
# metadata:
#   name: eventz-app-service
# spec:
#   selector:
#     app: eventz-app-node
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: eventz-app-node-service
  labels:
    app: eventz-app-node
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: eventz-app-node
  type: LoadBalancer
